### ISSUE TITLE
compiled error with provided inplementation, cudnn_conv_layer.cpp may be misgiven

### ISSUE THREAD

**Issue by SteveZeh** [limuhit/TrimmedConvolution#1]
Hi there, an issue occured when I compiled Caffe with provided layer implementation. I add/replace all the provided *.cu and *.cpp file under (caffe_dir)/src/caffe/layers, *.hpp under (caffe_dir)/include/caffe/layers and change the caffe.proto under (caffe_dir)/src/caffe/proto. But still got error when I compiled it.
```
src/caffe/layers/cudnn_conv_layer.cu(56): error: identifier "constrains_" is undefined
src/caffe/layers/cudnn_conv_layer.cu(62): error: identifier "group_in_" is undefined
src/caffe/layers/cudnn_conv_layer.cu(62): error: identifier "group_out_" is undefined
src/caffe/layers/cudnn_conv_layer.cu(66): error: identifier "group_in_" is undefined
src/caffe/layers/cudnn_conv_layer.cu(66): error: identifier "group_out_" is undefined
src/caffe/layers/cudnn_conv_layer.cu(109): error: identifier "conv_need_backward_" is undefined
```
I guess it may due to the cudnn_conv_layer.cpp is misgiven, since I find there is no variable above mentioned in cudnn_conv_layer.cpp. 
Thank you:)

**Comment by limuhit** [comment]
These parameters are defined in base_conv_layer.hpp, please check it. Actually, the cudnn_conv_layer inherit base_conv_layer. Thus, there should be no problem.

**Comment by SteveZeh** [comment]
Problem solved. I add 'this->' before those undefined variables in cudnn_conv_layer.cu, then I successfully compiled it. It may due to some compiler stuff, I compiled with CUDA 8.0, CUDNN 5.0, gcc 4.8.5 under centos 7.
BTW, I wrote a [simple installation guide](https://gist.github.com/SteveZeh/80613af6f5c5b1dacf743d31ac9e32e9) for noobs like me, if you don't mind.  Better than nothing. :P

**Comment by limuhit** [comment]
Thanks for the guidance.
